#define __SAME70Q21__
#include "cmsis/same70/include/same70.h"

#define AT91C_BASE_WDTC   WDT
#define WDTC_WDMR     WDT_MR
#define AT91C_WDTC_WDDIS  WDT_MR_WDDIS

#define AT91C_BASE_RSTC   RSTC
#define RSTC_RMR      RSTC_MR
#define AT91C_RSTC_URSTEN RSTC_MR_URSTEN

#define AT91C_BASE_PIOA   PIOA
#define PIO_PPUER     PIO_PUER
#define PIO_PPUDR     PIO_PUDR

#define AT91C_BASE_PMC    PMC
#define PMC_PCER      PMC_PCER0

#define AT91C_ID_PIOA   ID_PIOA
#define PIO_ASR			PIO_PER		// incorrect - the AB is split at a higher level

#define AT91C_PIO_PA0   PIO_PA0

#define AT91C_PIO_PA3   PIO_PA3
#define AT91C_PIO_PA4   PIO_PA4
#define AT91C_PIO_PA6   PIO_PA6
#define AT91C_PIO_PA8   PIO_PA8
#define AT91C_PIO_PA9   PIO_PA9

#define AT91C_PIO_PA10    PIO_PA10
#define AT91C_PIO_PA11    PIO_PA11
#define AT91C_PIO_PA12    PIO_PA12
#define AT91C_PIO_PA13    PIO_PA13
#define AT91C_PIO_PA14    PIO_PA14
#define AT91C_PIO_PA15    PIO_PA15
#define AT91C_PIO_PA16    PIO_PA16
#define AT91C_PIO_PA17    PIO_PA17
#define AT91C_PIO_PA18    PIO_PA18
#define AT91C_PIO_PA19    PIO_PA19
#define AT91C_PIO_PA20    PIO_PA20
#define AT91C_PIO_PA21    PIO_PA21
#define AT91C_PIO_PA22    PIO_PA22
#define AT91C_PIO_PA23    PIO_PA23
#define AT91C_PIO_PA24    PIO_PA24
#define AT91C_PIO_PA25    PIO_PA25
#define AT91C_PIO_PA26    PIO_PA26
#define AT91C_PIO_PA27    PIO_PA27
#define AT91C_PIO_PA28    PIO_PA28
#define AT91C_PIO_PA29    PIO_PA29
#define AT91C_PIO_PA30    PIO_PA30
#define AT91C_PIO_PA31    PIO_PA31

#define AT91C_PA5_RXD0    PIO_PB0C_RXD0
#define AT91C_PA6_TXD0    PIO_PB1C_TXD0

#define AT91C_BASE_SPI    SPI0
#define AT91C_SPI_SPIDIS  SPI_CR_SPIDIS
#define AT91C_SPI_SCBR    SPI_CSR_SCBR_Msk
#define AT91C_ID_SPI    ID_SPI0

#define AT91C_SPI_TXEMPTY   SPI_SR_TXEMPTY
#define AT91C_SPI_SWRST   0 // UNK! SPI_CR_SWRST
#define AT91C_SPI_MSTR    0 // UNK! SPI_MR_MSTR
#define AT91C_SPI_MODFDIS 0 // UNK! SPI_MR_MODFDIS
#define AT91C_SPI_CPOL    0 // UNK! SPI_CSR_CPOL
#define AT91C_SPI_SPIEN   0 // UNK! SPI_CR_SPIEN
#define AT91C_SPI_TDRE    0 // UNK! SPI_SR_TDRE
#define AT91C_SPI_RDRF    0 // UNK! SPI_SR_RDRF
#define AT91C_SPI_ENDTX   0 // UNK! SPI_SR_ENDTX
#define AT91C_SPI_ENDRX   0 // UNK! SPI_SR_ENDRX
#define SPI_PTSR SPI_SR // WRONG! Use XDMAC instead..
#define SPI_PTCR SPI_CR // WRONG! Use XDMAC instead..
#define SPI_RPR SPI_TDR // WRONG! Use XDMAC instead..
#define SPI_TPR SPI_TDR // WRONG! Use XDMAC instead..
#define SPI_RCR SPI_CR  // WRONG! Use XDMAC instead..
#define SPI_TCR SPI_CR  // WRONG! Use XDMAC instead..
#define SPI_RNCR SPI_CR // WRONG! Use XDMAC instead..
#define SPI_TNCR SPI_CR // WRONG! Use XDMAC instead..

#define AT91C_PA14_SPCK   PIO_PD22B_SPI0_SPCK
#define AT91C_PA13_MOSI   PIO_PD21B_SPI0_MOSI
#define AT91C_PA12_MISO   PIO_PD20B_SPI0_MISO

#define AT91C_BASE_US0    USART0
#define AT91C_US_RXRDY    US_IER_RXRDY
#define AT91C_ID_US0    ID_USART0
#define AT91C_US_RSTRX    US_CR_RSTRX
#define AT91C_US_RSTTX    US_CR_RSTTX
#define AT91C_US_RXDIS    US_CR_RXDIS
#define AT91C_US_TXDIS    US_CR_TXDIS
#define AT91C_US_RXEN   US_CR_RXEN
#define AT91C_US_TXEN   US_CR_TXEN
#define AT91C_US_USMODE_NORMAL  US_MR_USART_MODE_NORMAL
#define AT91C_US_CLKS_CLOCK   US_MR_USCLKS_MCK
#define AT91C_US_CHRL_8_BITS  US_MR_CHRL_8_BIT
#define AT91C_US_PAR_NONE   US_MR_PAR_NO
#define AT91C_US_NBSTOP_1_BIT US_MR_NBSTOP_1_BIT
#define AT91C_US_CHMODE_NORMAL  US_MR_CHMODE_NORMAL

#define US_PTCR US_CR  // WRONG! Use XDMAC instead..
#define US_TPR US_THR  // WRONG! Use XDMAC instead..
#define US_TCR US_CR   // WRONG! Use XDMAC instead..
#define US_TNPR US_THR // WRONG! Use XDMAC instead..
#define US_TNCR US_CR  // WRONG! Use XDMAC instead..

#define AT91C_PDC_TXTEN     0 // UNK! PERIPH_PTCR_TXTEN
#define AT91C_PDC_TXTDIS    0 // UNK! PERIPH_PTCR_TXTDIS
#define AT91C_PDC_RXTDIS    0 // UNK! PERIPH_PTCR_RXTDIS
#define AT91C_PDC_RXTEN     0 // UNK! PERIPH_PTCR_RXTEN

#define AT91C_BASE_SSC      SSC
#define AT91C_ID_SSC      ID_SSC
#define AT91C_SSC_CKO_DATA_TX SSC_RCMR_CKO_TRANSFER
#define AT91C_SSC_CKS_DIV   SSC_RCMR_CKS_MCK
#define AT91C_SSC_CKS_TK    SSC_RCMR_CKS_TK
#define AT91C_SSC_ENDTX     0 // UNK! SSC_SR_ENDTX
#define AT91C_SSC_MSBF      SSC_TFMR_MSBF
#define AT91C_SSC_RXDIS     SSC_CR_RXDIS
#define AT91C_SSC_RXEN      SSC_CR_RXEN
#define AT91C_SSC_START_CONTINOUS SSC_RCMR_START_CONTINUOUS
#define AT91C_SSC_START_TX    SSC_RCMR_START_TRANSMIT
#define AT91C_SSC_SWRST     SSC_CR_SWRST
#define AT91C_SSC_TXDIS     SSC_CR_TXDIS
#define AT91C_SSC_TXEN      SSC_CR_TXEN
#define AT91C_SSC_TXRDY     SSC_SR_TXRDY

#define SSC_PTCR SSC_CR  // WRONG! Use XDMAC instead..
#define SSC_TPR SSC_THR  // WRONG! Use XDMAC instead..
#define SSC_TCR SSC_CR   // WRONG! Use XDMAC instead..
#define SSC_RNCR SSC_CR  // WRONG! Use XDMAC instead..
#define SSC_TNCR SSC_CR  // WRONG! Use XDMAC instead..

#define AT91C_BASE_TWI      TWIHS0
#define AT91C_ID_TWI      ID_TWIHS0
#define AT91C_TWI_MREAD     TWIHS_MMR_MREAD
#define AT91C_TWI_MSDIS     TWIHS_CR_MSDIS
#define AT91C_TWI_MSEN      TWIHS_CR_MSEN
#define AT91C_TWI_RXRDY     TWIHS_SR_RXRDY
#define AT91C_TWI_START     TWIHS_CR_START
#define AT91C_TWI_STOP      TWIHS_CR_STOP
#define AT91C_TWI_SWRST     TWIHS_CR_SWRST
#define AT91C_TWI_TXCOMP    TWIHS_SR_TXCOMP
#define AT91C_TWI_TXRDY     TWIHS_SR_TXRDY
#define TWI_CR              TWIHS_CR
#define TWI_SR              TWIHS_SR
#define TWI_MMR             TWIHS_MMR
#define TWI_RHR             TWIHS_RHR
#define TWI_THR             TWIHS_THR
#define TWI_CWGR            TWIHS_CWGR
#define TWI_IADR            TWIHS_IADR

//#define AT91C_BASE_AIC  ??
#define AT91C_BASE_AIC		NVIC		// technically totally incorrect
#define AIC_IECR			ISER[0]
#define AIC_IDCR			ICER[0]
#define AIC_ICCR			ICPR[0]
#define AIC_SVR				IP
#define AIC_SMR				IP
#define AIC_SPU				STIR

//#define AT91C_BASE_PITC ??
#define AT91C_BASE_PITC		RTT			// close enough, but won't fly
#define PITC_PIMR			RTT_MR
#define PITC_PIIR			RTT_VR
#define AT91C_PITC_PITEN	RTT_MR_ALMIEN
#define AT91C_PITC_PICNT	RTT_VR_CRTV_Msk
#define AT91C_PITC_PIV		RTT_MR_RTPRES_Msk

//#define	AT91PS_UDP			UDP
//typedef Udp						*AT91PS_UDP;
typedef uint32_t				AT91_REG;
#define AT91C_BASE_UDP			UDP

#define UDP_RSTEP				UDP_RST_EP
#define AT91C_UDP_FEN			UDP_FADDR_FEN

#define UDP_GLBSTATE			UDP_GLB_STAT
#define AT91C_UDP_FADDEN		UDP_GLB_STAT_FADDEN
#define AT91C_UDP_CONFG			UDP_GLB_STAT_CONFG

#define AT91C_UDP_ENDBUSRES		UDP_ISR_ENDBUSRES
#define AT91C_UDP_EPINT0		UDP_ISR_EP0INT

#define AT91C_UDP_RX_DATA_BK0	UDP_CSR_RX_DATA_BK0
#define AT91C_UDP_RX_DATA_BK1	UDP_CSR_RX_DATA_BK1
#define AT91C_UDP_TXPKTRDY		UDP_CSR_TXPKTRDY
#define AT91C_UDP_TXCOMP		UDP_CSR_TXCOMP
#define AT91C_UDP_FORCESTALL	UDP_CSR_FORCESTALL
#define AT91C_UDP_ISOERROR		UDP_CSR_ISOERROR
#define AT91C_UDP_RXSETUP		UDP_CSR_RXSETUP
#define AT91C_UDP_DIR			UDP_CSR_DIR
#define AT91C_UDP_EPEDS			UDP_CSR_EPEDS
#define AT91C_UDP_STALLSENT		UDP_CSR_STALLSENT
#define AT91C_UDP_EPTYPE_CTRL		UDP_CSR_EPTYPE_CTRL
#define AT91C_UDP_EPTYPE_BULK_OUT	UDP_CSR_EPTYPE_BULK_OUT
#define AT91C_UDP_EPTYPE_BULK_IN	UDP_CSR_EPTYPE_BULK_IN
#define AT91C_UDP_EPTYPE_ISO_OUT	UDP_CSR_EPTYPE_ISO_OUT
#define AT91C_UDP_EPTYPE_ISO_IN		UDP_CSR_EPTYPE_ISO_IN
#define AT91C_UDP_EPTYPE_INT_OUT	UDP_CSR_EPTYPE_INT_OUT
#define AT91C_UDP_EPTYPE_INT_IN		UDP_CSR_EPTYPE_INT_IN

#define AT91C_BASE_CKGR			PMC
#define CKGR_PLLR				CKGR_PLLAR
#define AT91C_PMC_UDP			PMC_SCER_UDP
#define AT91C_CKGR_USBDIV_1		PMC_USB_USBDIV(2)
#define AT91C_ID_UDP			(7) 	// incorrect - UDP is system, not peripheral
#define PMC_MOR					CKGR_MOR

#define AT91C_CKGR_MOSCEN		CKGR_MOR_MOSCXTEN
#define AT91C_CKGR_OSCOUNT		CKGR_MOR_MOSCXTST_Msk
#define AT91C_PMC_MOSCS			PMC_SR_MOSCXTS
#define PMC_PLLR				CKGR_PLLAR

#define AT91C_CKGR_MUL			CKGR_PLLAR_MULA_Msk
#define AT91C_CKGR_DIV			CKGR_PLLAR_DIVA_Msk
#define AT91C_PMC_LOCK			PMC_SR_LOCKA
#define AT91C_PMC_MCKRDY		PMC_SR_MCKRDY
#define AT91C_PMC_PRES_CLK_2	PMC_MCKR_PRES_CLK_2
#define AT91C_PMC_CSS_PLL_CLK	PMC_MCKR_CSS_PLLA_CLK

#define AT91C_BASE_MC				EFC
#define MC_FMR						EEFC_FMR
#define AT91C_MC_FWS_1FWS			EEFC_FMR_FWS(1)
#define AT91C_MC_FSR				(&REG_EFC0_FSR)
#define AT91C_MC_FCR				(&REG_EFC0_FCR)
#define AT91C_MC_FCMD_START_PROG	EEFC_FCR_FCMD_WP
#define AT91C_MC_FRDY				EEFC_FSR_FRDY


//#define PIO_ASR ?? PIO_ABCDSR ??

#define  AT91C_IFLASH_NB_OF_PAGES	640 // ??
#define  AT91C_IFLASH_PAGE_SIZE		256 // ??
