#define __SAM4SD32B__ // __SAM4SD32C__
#include "cmsis/sam4s/include/sam4s.h"

#define AT91C_BASE_WDTC 	WDT
#define WDTC_WDMR			WDT_MR
#define AT91C_WDTC_WDDIS 	WDT_MR_WDDIS

#define AT91C_BASE_RSTC		RSTC
#define RSTC_RMR			RSTC_MR
#define AT91C_RSTC_URSTEN	RSTC_MR_URSTEN

#define AT91C_BASE_PIOA		PIOA
#define PIO_PPUER			PIO_PUER
#define PIO_PPUDR			PIO_PUDR

#define AT91C_BASE_PMC		PMC
#define PMC_PCER			PMC_PCER0

#define AT91C_ID_PIOA		ID_PIOA

#define AT91C_PIO_PA6		PIO_PA6
#define AT91C_PIO_PA8		PIO_PA8
#define AT91C_PIO_PA9		PIO_PA9
#define AT91C_PIO_PA10		PIO_PA10
#define AT91C_PIO_PA11		PIO_PA11
#define AT91C_PIO_PA12		PIO_PA12
#define AT91C_PIO_PA13		PIO_PA13
#define AT91C_PIO_PA14		PIO_PA14
#define AT91C_PIO_PA15		PIO_PA15
#define AT91C_PIO_PA16		PIO_PA16
#define AT91C_PIO_PA20		PIO_PA20
#define AT91C_PIO_PA22		PIO_PA22
#define AT91C_PIO_PA25		PIO_PA25
#define AT91C_PIO_PA29		PIO_PA29
#define AT91C_PIO_PA30		PIO_PA30
#define AT91C_PIO_PA31		PIO_PA31

#define AT91C_PA5_RXD0		PIO_PA5A_RXD0
#define AT91C_PA6_TXD0		PIO_PA6A_TXD0

#define AT91C_BASE_SPI		SPI
#define AT91C_SPI_SPIDIS	SPI_CR_SPIDIS
#define AT91C_ID_SPI		ID_SPI

#define AT91C_BASE_US0		USART0
#define AT91C_US_RXRDY		US_IER_RXRDY
#define AT91C_ID_US0		ID_USART0
#define AT91C_US_RSTRX		US_CR_RSTRX
#define AT91C_US_RSTTX		US_CR_RSTTX
#define AT91C_US_RXDIS		US_CR_RXDIS
#define AT91C_US_TXDIS		US_CR_TXDIS
#define AT91C_US_RXEN		US_CR_RXEN
#define AT91C_US_TXEN		US_CR_TXEN
#define AT91C_US_USMODE_NORMAL	US_MR_USART_MODE_NORMAL
#define AT91C_US_CLKS_CLOCK	US_MR_USCLKS_MCK
#define AT91C_US_CHRL_8_BITS	US_MR_CHRL_8_BIT
#define AT91C_US_PAR_NONE	US_MR_PAR_NO
#define AT91C_US_NBSTOP_1_BIT	US_MR_NBSTOP_1_BIT
#define AT91C_US_CHMODE_NORMAL	US_MR_CHMODE_NORMAL
